CREATE TABLE `order_items` (
  `order_item_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `quantity` VARCHAR(50) NOT NULL,
  `unit_price` VARCHAR(50) NOT NULL,

  `order_id` BIGINT(20) UNSIGNED NOT NULL,
   FOREIGN KEY (`order_id`) REFERENCES `orders`(`order_id`) ON DELETE RESTRICT ON UPDATE CASCADE,

   `product_id` BIGINT(20) UNSIGNED NOT NULL,
    FOREIGN KEY (`product_id`) REFERENCES `products`(`product_id`) ON DELETE RESTRICT ON UPDATE CASCADE
)